"""HTML Report Generator."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from reconai.core.database.manager import DatabaseManager


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ReconAI Report — {target}</title>
<style>
  :root {{ --bg:#0d1117;--card:#161b22;--border:#30363d;--text:#c9d1d9;--accent:#58a6ff;--critical:#f85149;--high:#d29922;--medium:#3fb950;--low:#8b949e; }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ background:var(--bg); color:var(--text); font-family:'Segoe UI',system-ui,sans-serif; padding:2rem; }}
  h1 {{ color:var(--accent); font-size:2rem; margin-bottom:0.25rem; }}
  h2 {{ color:var(--accent); font-size:1.25rem; margin:2rem 0 1rem; border-bottom:1px solid var(--border); padding-bottom:0.5rem; }}
  .meta {{ color:var(--low); font-size:0.85rem; margin-bottom:2rem; }}
  .score-box {{ display:inline-block; padding:1rem 2rem; border-radius:8px; background:var(--card); border:2px solid var(--border); margin-bottom:2rem; text-align:center; }}
  .score-box .score {{ font-size:3rem; font-weight:700; color:var(--accent); }}
  .score-box .grade {{ font-size:1.5rem; color:var(--high); }}
  .stats-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:1rem; margin-bottom:2rem; }}
  .stat-card {{ background:var(--card); border:1px solid var(--border); border-radius:8px; padding:1rem; text-align:center; }}
  .stat-card .val {{ font-size:2rem; font-weight:700; color:var(--accent); }}
  .stat-card .lbl {{ font-size:0.8rem; color:var(--low); }}
  table {{ width:100%; border-collapse:collapse; background:var(--card); border-radius:8px; overflow:hidden; margin-bottom:2rem; }}
  th {{ background:var(--border); padding:0.75rem 1rem; text-align:left; font-size:0.85rem; color:var(--text); }}
  td {{ padding:0.75rem 1rem; border-top:1px solid var(--border); font-size:0.85rem; }}
  .sev-critical {{ color:var(--critical); font-weight:700; }}
  .sev-high {{ color:var(--high); font-weight:700; }}
  .sev-medium {{ color:var(--medium); }}
  .sev-low {{ color:var(--low); }}
  .sev-info {{ color:var(--low); opacity:.7; }}
  .badge {{ display:inline-block; padding:2px 8px; border-radius:4px; font-size:0.75rem; font-weight:700; text-transform:uppercase; }}
  .badge-aws {{ background:#ff9900; color:#111; }}
  .badge-gcp {{ background:#4285f4; color:#fff; }}
  .badge-azure {{ background:#0089d6; color:#fff; }}
  .badge-other {{ background:var(--border); color:var(--text); }}
  .public-tag {{ color:var(--critical); font-weight:700; }}
  .writable-tag {{ background:var(--critical); color:#fff; padding:2px 6px; border-radius:4px; font-weight:700; }}
</style>
</head>
<body>
<h1>&#128270; ReconAI Attack Surface Report</h1>
<div class="meta">
  <strong>Target:</strong> {target} &nbsp;|&nbsp;
  <strong>Scan ID:</strong> {scan_id} &nbsp;|&nbsp;
  <strong>Date:</strong> {date} &nbsp;|&nbsp;
  <strong>Duration:</strong> {duration}s
</div>

<h2>Risk Assessment</h2>
<div class="score-box">
  <div class="score">{risk_score}</div>
  <div>/100</div>
  <div class="grade">Grade: {risk_grade}</div>
</div>

<h2>Attack Surface Overview</h2>
<div class="stats-grid">
  {stats_cards}
</div>

<h2>Security Findings</h2>
{findings_table}

<h2>Cloud Assets & Storage ({cloud_count})</h2>
{cloud_table}

<h2>Subdomains ({sub_count})</h2>
{subdomains_table}

<h2>Open Ports</h2>
{ports_table}

<h2>Technologies Detected</h2>
{techs_table}

<footer style="margin-top:4rem;color:var(--low);font-size:0.75rem;text-align:center;">
  Generated by ReconAI &mdash; For authorized use only
</footer>
</body>
</html>"""


def _stat_card(label: str, value: int | str) -> str:
    return f'<div class="stat-card"><div class="val">{value}</div><div class="lbl">{label}</div></div>'


def _sev_class(severity: str) -> str:
    return f"sev-{severity.lower()}"


def generate_html_report(db: "DatabaseManager", scan_id: str, out_dir: Path) -> Path:
    """Generate a full HTML report from scan data."""
    from reconai.reports.scoring import RiskScoringEngine

    scan = db.get_scan(scan_id)
    if not scan:
        raise ValueError(f"Scan {scan_id} not found")

    stats = db.get_scan_stats(scan_id)
    findings = db.get_findings(scan_id)
    subs = db.get_subdomains(scan_id)
    ports = db.get_ports(scan_id)
    techs = db.get_technologies(scan_id)
    cloud_assets = db.get_cloud_assets(scan_id)
    risk = RiskScoringEngine(db, scan_id).calculate_score()

    # Stats cards
    stats_cards = "".join([
        _stat_card("Subdomains", stats.get("subdomains", 0)),
        _stat_card("Open Ports", stats.get("ports", 0)),
        _stat_card("URLs", stats.get("urls", 0)),
        _stat_card("Technologies", stats.get("technologies", 0)),
        _stat_card("Findings", stats.get("findings", 0)),
        _stat_card("Cloud Assets", stats.get("cloud_assets", 0)),
        _stat_card("Certificates", stats.get("certificates", 0)),
    ])

    # Findings table
    if findings:
        rows = "".join(
            f'<tr><td class="{_sev_class(f["severity"])}">{f["severity"].upper()}</td>'
            f'<td>{f["title"]}</td><td>{f["affected_asset"]}</td>'
            f'<td>{f["confidence"]}</td></tr>'
            for f in findings
        )
        findings_table = f'<table><tr><th>Severity</th><th>Title</th><th>Asset</th><th>Confidence</th></tr>{rows}</table>'
    else:
        findings_table = "<p>No security findings discovered.</p>"

    # Cloud Assets table
    if cloud_assets:
        def _prov_badge(prov: str) -> str:
            p = prov.lower()
            badge_cls = f"badge-{p}" if p in ("aws", "gcp", "azure") else "badge-other"
            return f'<span class="badge {badge_cls}">{prov.upper()}</span>'

        c_rows = []
        for c in cloud_assets:
            pub_tag = '<span class="public-tag">🚨 PUBLIC</span>' if c.get("is_public") else '<span style="color:var(--low);">Private</span>'
            writ_tag = '<span class="writable-tag">⚠️ WRITABLE</span>' if c.get("is_writable") else '<span style="color:var(--low);">Read-Only</span>'
            url = c.get("url", "")
            link = f'<a href="{url}" target="_blank" style="color:var(--accent);text-decoration:none;">{c.get("asset_name")}</a>' if url else c.get("asset_name")
            c_rows.append(
                f'<tr><td>{_prov_badge(c.get("provider", ""))}</td>'
                f'<td>{c.get("asset_type", "").replace("_", " ").title()}</td>'
                f'<td>{link}</td>'
                f'<td>{pub_tag}</td>'
                f'<td>{writ_tag}</td></tr>'
            )
        cloud_table = (
            '<table><tr><th>Provider</th><th>Type</th><th>Asset Name / URL</th>'
            '<th>Exposure</th><th>Permission</th></tr>' + "".join(c_rows) + '</table>'
        )
    else:
        cloud_table = "<p>No cloud assets or storage buckets discovered.</p>"

    # Subdomains table
    if subs:
        rows = "".join(f'<tr><td>{s["subdomain"]}</td><td>{"&#9989;" if s["is_alive"] else ""}</td></tr>' for s in subs[:100])
        subdomains_table = f'<table><tr><th>Subdomain</th><th>Alive</th></tr>{rows}</table>'
        if len(subs) > 100:
            subdomains_table += f'<p style="color:var(--low);">... and {len(subs)-100} more in JSON report.</p>'
    else:
        subdomains_table = "<p>No subdomains discovered.</p>"

    # Ports table
    if ports:
        rows = "".join(
            f'<tr><td>{p["host"]}</td><td>{p["port"]}/{p["protocol"]}</td>'
            f'<td>{p["service"]}</td><td>{p["product"]} {p["version"]}</td></tr>'
            for p in ports
        )
        ports_table = f'<table><tr><th>Host</th><th>Port</th><th>Service</th><th>Product/Version</th></tr>{rows}</table>'
    else:
        ports_table = "<p>No open ports discovered.</p>"

    # Techs table
    if techs:
        rows = "".join(f'<tr><td>{t["name"]}</td><td>{t["version"]}</td><td>{t["category"]}</td><td>{t["host"]}</td></tr>' for t in techs)
        techs_table = f'<table><tr><th>Technology</th><th>Version</th><th>Category</th><th>Host</th></tr>{rows}</table>'
    else:
        techs_table = "<p>No technologies detected.</p>"

    html = _HTML_TEMPLATE.format(
        target=scan["target"],
        scan_id=scan_id,
        date=scan["started_at"],
        duration=f"{scan['duration']:.1f}",
        risk_score=risk["score"],
        risk_grade=risk["grade"],
        stats_cards=stats_cards,
        findings_table=findings_table,
        cloud_count=len(cloud_assets),
        cloud_table=cloud_table,
        sub_count=len(subs),
        subdomains_table=subdomains_table,
        ports_table=ports_table,
        techs_table=techs_table,
    )

    out_file = out_dir / "report.html"
    out_file.write_text(html, encoding="utf-8")
    return out_file
